# Starting scene ID
start: "scene1"

# Video file paths for each scene
videos:
  scene1: "videos/video1.mp4"
  iscene1.1: "videos/video2.mp4"
  iscene1.2: "videos/video3.mp4"
  scene2: "videos/video4.mp4"
  iscene2.3: "videos/video5.mp4"
  iscene2.4: "videos/video6.mp4"
  scene3: "videos/video7.mp4"
  scene4: "videos/video8.mp4"
  scene5: "videos/video9.mp4"
  scene6: "videos/video10.mp4"
  scene7: "videos/video1.mp4"
  s1.3: "videos/video2.mp4"
  s1.4: "videos/video3.mp4"
  i1.4.1: "videos/video4.mp4"
  s1.5: "videos/video5.mp4"
  s1.6: "videos/video6.mp4"

# Options for each scene
options:
  # Question scene
  scene1:
    scene_type: Question
    question_heading: "Choose your adventure:"   
    choices:
      "scene 1 option 1":
        next: s1.3
        image: "images/q1.jpg"
      "scene 2 option 2":
        next: scene3
        image: "images/q1.jpg"
      "interrupt option":
        next: iscene1.1
        image: "images/m2.jpg"
        temporary: true
      "interrupt option 2":
        next: iscene1.2
        image: "images/m1.jpg"
        temporary: true
  
  s1.3:
    scene_type: Main
    main_heading: "This is the main part of the script"
    choices:
      "Option 1":
        next: s1.3
        image: "images/m1.jpg"
      "option 2":
        next: s1.4
        image: "images/m2.jpg"
      "option 3":
        next: s1.5
        image: "images/m3.jpg"
      "option 4":
        next: s1.6
        image: "images/m4.jpg"
        
  s1.4:
    scene_type: Main
    main_heading: "This is the main part of the script"
    choices:
      "Option 1":
        next: s1.3
        image: "images/m1.jpg"
      "option 2":
        next: s1.4
        image: "images/m2.jpg"
      "option 3":
        next: s1.5
        image: "images/m3.jpg"
      "option 4":
        next: s1.6
        image: "images/m4.jpg"
      "temporary interrupt option":
        next: i1.4.1 
        image: "images/m1.jpg"  
        temporary: true
        
  s1.5:
    scene_type: Main
    main_heading: "This is the main part of the script"
    choices:
      "Option 1":
        next: s1.3
        image: "images/m1.jpg"
      "option 2":
        next: s1.4
        image: "images/m2.jpg"
      "option 3":
        next: s1.5
        image: "images/m3.jpg"
      "option 4":
        next: s1.6
        image: "images/m4.jpg"
    
  s1.6:
    scene_type: Main
    main_heading: "This is the main part of the script"
    choices:
      "Option 1":
        next: s1.3
        image: "images/m1.jpg"
      "option 2":
        next: s1.4
        image: "images/m2.jpg"
      "option 3":
        next: s1.5
        image: "images/m3.jpg"
      "option 4":
        next: s1.6
        image: "images/m4.jpg"

  # Scene with temporary interrupt choices
  scene2:
    scene_type: Continue
    continue_heading: "You took the left path. Watch out for surprises!"
    choices:
      "scene 2 option 1":
        next: scene4
        image: "images/11.jpg"
      "scene 2 option 2":
        next: scene5
        image: "images/q2.jpg"
      "scene 2 interrupt 1":
        next: iscene2.3
        image: "images/m1.jpg"
        temporary: true
      "scene 2 interrup 2":
        next: iscene2.4
        image: "images/m2.jpg"
        temporary: true

  # Another main scene for free exploration
  scene3:
    scene_type: Question
    main_heading: "You're on the right path, where to next?"
    choices:
      "Head to the Mountain":
        next: scene4
        image: "images/q2.jpg"
      "go to scene5":
        next: scene5    
        image: "images/q1.jpg"

  # Mountain Path - Continue Scene
  scene4:
    scene_type: Continue
    continue_heading: "You are now climbing the mountain!"
    choices:
      "Reach the Summit":
        next: scene7
        image: "images/q3.jpg"

  # Forest Path - Question Scene
  scene5:
    scene_type: Question
    question_heading: "You encountered a wild animal. What will you do?"
    choices:
      "Run Away":
        next: scene7
        image: "images/q2.jpg"
      "Try to Calm It":
        next: scene7
        image: "images/q4.jpg"

  # Bonus Scene
  scene6:
    scene_type: Continue
    continue_heading: "Enjoy this bonus content!"
    choices:
      "Back to Main Menu":
        next: scene1
        image: "images/q4.jpg"

  # Outro Scene
  scene7:
    scene_type: Continue
    continue_heading: "Thank you for playing!"
    choices:
      "Restart":
        next: scene1
        image: "images/q1.jpg"
